version: '3.8'
services:
  emotion_recognition:
    build:
      context: ./emotion_recognition
      target: emotion_recognition-docker
    container_name: emotion_recognition
  text_to_speech:
      build:
        context: ./text_to_speech
        target: text_to_speech-docker
      container_name: text_to_speech
  speech_to_text:
    build:
      context: ./speech_to_text
      target: speech_to_text-docker
    container_name: speech_to_text